documentation: 
  baseurl: http://localhost
  swagger: 
    services:
      user-management
        url: ${documentation.baseurl}:${services.user-management.port}/api-docs/users
        tag: users
        
services: 
  user-management:
    port: 3000
    tag: users
